### PR TITLE
fix: check if gas price is greater than the tip

### LINKED ISSUE #32: Issue with fee estimation in Gnosis Mainnet
Increase the base fee in a way that will cover fees for upcoming Erigon blocks

### PR DESCRIPTION
**Pull request by blockchainluffy**

### CODE REVIEW

File: utils/utils.go [hunk 1]
```diff
@@ -160,6 +160,9 @@ func MinGasTipUpdateFn(suggestedGasTipCap *big.Int, suggestedGasPrice *big.Int,
 	if suggestedGasTipCap.Cmp(GweiGasTip) < 0 {
 		return big.NewInt(0).Add(GweiGasTip, suggestedGasPrice), GweiGasTip
 	}
+	if suggestedGasTipCap.Cmp(suggestedGasPrice) > 0 {
```
Comment (ylembachar) [inline utils/utils.go]: Since we are using the suggested gas price which is only a heuristic and should in theory include both the gas price and the fee, we can just raise the max fee cap to the suggested gas tip, instead of adding them up, in order to make sure the price is compliant.

Comment (blockchainluffy) [reply utils/utils.go]: after discussion, we decided to do trial for above approach and see if it works with some additional logs

**Review by ylembachar — APPROVED** [review]
